app.name=Demo Project
app.port=8086

app.profile=dev

app.context=/api/v1

cors.origin=http://localhost:4200

#SECURITY_NAME=admin
#SECURITY_PASSWORD=admin

app.swaggerUrl=/api/v1/swagger-ui/index.html
app.actuatorUrl=/api/v1/actuator