#import properties files
spring.config.import=application_prod.properties,application_dev.properties,optional:file:./config.properties


spring.application.name=${app.name}


#context configuration
server.servlet.context-path=${app.context}

#profile
spring.profiles.active=${app.profile:dev}


springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=/v3/api-docs

